# Concat and Append

In [ ]:
# Start writing code here...

import numpy as np
import pandas as pd

In [ ]:
def make_df(cols,ind):
    data = {c:[str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data,ind)


In [ ]:
make_df("abc",range(3))

a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2

In [ ]:
X = [2,4,5,6,7]
Y = [7, 8, 9,8]

In [ ]:
np.concatenate([X,Y])

array([2, 4, 5, 6, 7, 7, 8, 9, 8])

In [ ]:
X = np.array([[1,2],[3,4]])

In [ ]:
np.concatenate([X,X],axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [ ]:
np.concatenate([X,X],axis=0)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [ ]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])

In [ ]:
pd.concat([ser1,ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [ ]:
df1 = make_df("AB",[1,2])
df2 = make_df("AB",[3,4])

In [ ]:
pd.concat([df1,df2])

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [ ]:
x = make_df('AB', [0, 1])
y = make_df('AB', [2, 3])


In [ ]:
y.index = x.index

In [ ]:
pd.concat([x,y])

A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3

In [ ]:
pd.concat([x,y],ignore_index=True)

A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [ ]:
pd.concat([x, y], keys=['x', 'y'])

A   B
x 0  A0  B0
  1  A1  B1
y 0  A2  B2
  1  A3  B3

In [ ]:
df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [3, 4])

In [ ]:
df5

A   B   C
1  A1  B1  C1
2  A2  B2  C2

In [ ]:
df6

B   C   D
3  B3  C3  D3
4  B4  C4  D4

In [ ]:
pd.concat([df5, df6])

A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

In [ ]:
pd.concat([df5, df6],join='inner')

B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

In [ ]:
df1.append(df2)

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [ ]:
df1

A   B
1  A1  B1
2  A2  B2

In [ ]:
df2

A   B
3  A3  B3
4  A4  B4

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=f5f90ba1-3290-463e-8fc6-44108f4fa21b' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>