In [1]:
import numpy as np

In [3]:
salaries = np.genfromtxt('data/salary.csv', delimiter=',')

In [4]:
salaries

array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

In [5]:
salaries.shape

(1147,)

### argmax

Returns the indices of the maximum values along an axis.

In [6]:
np.argmax(salaries)

246

In [7]:
salaries[246]

850000.0

### argmin

Returns the indices of the minimum values along an axis.

In [8]:
np.argmin(salaries)

282

In [9]:
salaries[282]

11400.0

### argsort

Returns the indices that would sort an array.

In [45]:
np.argsort(salaries)

array([282, 969, 606, ..., 829, 389, 246])

##### Specify a sorting algorithm
Perform an indirect sort along the given axis using the algorithm specified by the kind keyword. It returns an array of indices of the same shape as a that index data along the given axis in sorted order.

In [46]:
np.argsort(salaries,kind='mergesort')

array([282, 969, 606, ..., 829, 389, 246])

##### View the sorted salary values

In [10]:
salaries[np.argsort(salaries,kind='mergesort')]

array([ 11400.,  11642.,  12000., ..., 680000., 820000., 850000.])

The functions <b> max , min , sort </b> gives the respective elements itself instead of indices.

### where

The where() function returns the indices of elements in an input array where the given condition is satisfied.

In [11]:
greater_than_100 = np.where(salaries > 100000)

In [12]:
greater_than_100

(array([  22,   27,   33,   45,   48,   59,   77,   78,   87,   91,   94,
         102,  109,  117,  123,  151,  221,  236,  242,  243,  246,  271,
         296,  297,  303,  337,  343,  378,  385,  389,  402,  408,  432,
         436,  450,  454,  503,  504,  538,  560,  563,  580,  581,  602,
         607,  687,  701,  728,  736,  745,  769,  779,  802,  819,  822,
         829,  859,  913,  922,  946,  949,  977,  980,  998, 1019, 1033,
        1062, 1065, 1104, 1105, 1112, 1130]),)

In [15]:
len(greater_than_100[0])

72

In [55]:
salaries[greater_than_100]

array([261546., 500000., 120000., 210000., 105227., 115000., 130773.,
       103529., 119875., 132000., 141671., 109100., 550000., 180000.,
       220000., 109294., 135380., 103529., 120000., 185000., 850000.,
       181339., 111600., 102000., 625000., 110464., 102000., 140000.,
       120000., 820000., 250000., 130000., 136375., 141000., 142800.,
       116626., 110000., 130000., 444000., 116000., 110000., 113996.,
       160000., 150000., 108000., 120000., 120000., 220000., 117701.,
       120000., 120010., 110000., 103645., 102000., 108977., 680000.,
       152568., 114800., 150000., 111841., 110000., 108000., 102000.,
       134449., 120000., 101349., 120000., 250000., 175000., 261546.,
       120000., 103000.])

### extract
The extract() function returns the elements satisfying any condition

##### Start off by defining a condition

In [16]:
condition = salaries > np.mean(salaries)

##### Use the condition in the extract function

In [17]:
np.extract(condition, salaries)

array([ 60000.,  58000.,  56967.,  70000.,  75000.,  62000.,  56000.,
       261546.,  77000., 500000.,  77570.,  60000.,  65000.,  60000.,
       120000.,  81000.,  75000.,  75000.,  73000.,  75000., 210000.,
        90000., 105227.,  84000.,  98000.,  70000., 115000.,  72000.,
        57400.,  70000.,  71796., 130773., 103529.,  57000.,  70000.,
        75000.,  57000., 119875.,  60000., 132000., 100000., 141671.,
        87500.,  90000.,  65000., 109100.,  98080.,  87689., 550000.,
        56697.,  60000., 180000.,  92000.,  63000., 220000.,  66000.,
        80000.,  65460.,  65000., 109294.,  70000.,  57758.,  75000.,
        75000.,  62662.,  64000.,  90000.,  60000.,  60000.,  70000.,
        63000.,  80000.,  70000.,  60000.,  90000., 135380.,  65000.,
        70000., 103529.,  64000.,  70000., 120000., 185000.,  70000.,
       850000.,  61500.,  60000.,  63000., 181339.,  75665.,  58000.,
        57000., 100000.,  65000.,  62662.,  90000.,  70835.,  75000.,
       111600., 1020